# Usar uma imagem oficial do Python como base
FROM python:3.11-slim

# Instalar dependências necessárias
RUN apt-get update && apt-get install -y \
    wget \
    curl \
    gnupg \
    unzip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Instalar o Google Chrome
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list && \
    apt-get update && apt-get install -y google-chrome-stable && \
    rm -rf /var/lib/apt/lists/*

# Baixar o ChromeDriver e configurá-lo no PATH
RUN CHROMEDRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE) && \
    wget -N https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip -P ~ && \
    unzip ~/chromedriver_linux64.zip -d ~ && \
    rm ~/chromedriver_linux64.zip && \
    mv ~/chromedriver /usr/local/bin/chromedriver && \
    chmod +x /usr/local/bin/chromedriver

# Criar um diretório de trabalho
WORKDIR /app

# Copiar o arquivo de requirements para o contêiner
COPY . .

# Instalar as dependências Python
RUN pip install --no-cache-dir -r requirements.txt

# Comando padrão para o contêiner
CMD ["sleep", "infinity"]
# CMD ["python3", "scraping.py"]
